apiVersion: v1
kind: Pod
metadata:
  name: pd-pod-test
spec:
  volumes:
    - name: cvmfs
      emptyDir: {}
    - name: config-volume
      configMap:
        name: wn-config
    - name: pool-password-volume
      secret:
        secretName: pool-password
        defaultMode: 0600
  containers:
    - name: wn-cvmfs  
      image: ttedesch/wn-cvmfs:v0.0.2
      env:
      - name: REPO_LIST
        value: "oasis.opensciencegrid.org unpacked.cern.ch cms.cern.ch sft.cern.ch"
      resources:
        requests:
          memory: "64Mi"
          cpu: "5"
      securityContext:
        privileged: true
      volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
        - name: config-volume
          mountPath: /etc/condor/config.d/99_custom_config
          subPath: 99_custom_config
        - name: pool-password-volume
          mountPath: /etc/pwd
