---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk-ba-new
  labels:
    nodeName: vk-ba-new
spec:
  replicas: 1
  selector:
    matchLabels:
      nodeName: vk-ba-new
  template:
    metadata:
      labels:
        nodeName: vk-ba-new
    spec:
      containers:
      #- name: settoken
      #  image: "docker.io/alpine:3"
      #  command: ["sh", "-c"]
      #  args: ["touch /opt/interlink/token"]
      #  volumeMounts:
      #  - name: token
      #    mountPath: /opt/interlink
      - name: jaeger
        image: jaegertracing/all-in-one:1.51
      - name: inttw-vk
        image: ghcr.io/intertwin-eu/virtual-kubelet-inttw:latest 
        #image: dciangot/vk:latest
        imagePullPolicy: Always
        #command: ["sleep", "infinity"]
        env:
        - name: NODENAME
          value: vk-ba-new
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBECONFIG
          value: "/etc/interlink/kubeconfig"
        - name: KUBELET_PORT
          value: "10255"
        - name: INTERLINKCONFIGPATH
          value: "/etc/interlink/InterLinkConfig-ba.yaml"
        - name: VKTOKENFILE
          value: "/opt/interlink/token"
        - name: CONFIGPATH
          value: "/etc/interlink/vk-cfg.json"
        volumeMounts:
        - name: config
          mountPath: /etc/interlink/InterLinkConfig-ba.yaml
          subPath: InterLinkConfig-ba.yaml
        - name: config-json
          mountPath: /etc/interlink/vk-cfg.json
          subPath: vk-cfg.json
        - name: config
          mountPath: /etc/interlink/kubeconfig
          subPath: kubeconfig
        - name: token
          mountPath: /opt/interlink
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 50m
            memory: 100Mi
      - name: refresh-token
        image: ghcr.io/intertwin-eu/virtual-kubelet-inttw-refresh:latest
        imagePullPolicy: Always
        env:
        - name: IAM_SERVER
          value: "https://dodas-iam.cloud.cnaf.infn.it/"
        # TODO load env IAM client from secret
        - name: IAM_CLIENT_ID
          value: "DUMMY"
        - name: IAM_CLIENT_SECRET
          value: "DUMMY"
        - name: IAM_REFRESH_TOKEN
          value: "DUMMY"
        - name: IAM_VK_AUD
          value: intertw-vk
        - name: TOKEN_PATH
          value: /opt/interlink/token
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - name: token
          mountPath: /opt/interlink
      serviceAccountName: interlink
      volumes:
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: vk-ba-new-config
      - name: config-json
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: vk-ba-new-cfg
      - name: token
        emptyDir: {}
