InterlinkPort: "30004"
SidecarPort: "8003"
SbatchPath: "/usr/bin/sbatch"
ScancelPath: "/usr/bin/scancel"
CommandPrefix: ""
ExportPodData: true
DataRootFolder: ".knoc/"
VKTokenFile: "$HOME/interLink/token"
InterlinkURL: "http://192.168.0.200"
SidecarURL: "http://192.168.0.200"
SqueuePath: "/usr/bin/squeue"
ServiceAccount: "interlink"
Namespace: "af-new"
Tsocks: false
TsocksPath: "$WORK/tsocks-1.8beta5+ds1/libtsocks.so"
TsocksLoginNode: "login01"
BashPath: /bin/bash
VerboseLogging: true
ErrorsOnlyLogging: false
